# Generated by Django 4.2 on 2023-04-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("title", models.CharField(max_length=300)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
