# Generated by Django 4.2 on 2023-06-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="expenses.tag"
            ),
        ),
    ]
