# Generated by Django 4.2 on 2023-06-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_tag_expense_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_starred",
            field=models.BooleanField(default=False),
        ),
    ]
